import {createPortal} from 'react-dom';
import React,{useEffect,useRef,useState} from 'react';
export default function AchievementCollage({photos,paused=false}){
 const [placements,setPlacements]=useState([]);const started=useRef(false);
 const opener=useRef(null);const [detail,setDetail]=useState(null);const box=useRef(null);const [inView,setInView]=useState(false),[landed,setLanded]=useState(0),[reduce,setReduce]=useState(false);
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setReduce(mq.matches);sync();mq.addEventListener('change',sync);return()=>mq.removeEventListener('change',sync)},[]);
 useEffect(()=>{setPlacements(photos.map((_,i)=>({x:28+(i%4)*14+(Math.random()-.5)*8,y:35+Math.floor(i/4)*10+(Math.random()-.5)*8,r:(Math.random()-.5)*28,order:Math.random()})).sort((a,b)=>a.order-b.order));},[]);
 useEffect(()=>{const obs=new IntersectionObserver(es=>{if(es[0].isIntersecting){setInView(true);obs.disconnect()}},{threshold:.2});if(box.current)obs.observe(box.current);return()=>obs.disconnect()},[]);
 useEffect(()=>{if(paused||reduce){setLanded(photos.length);started.current=true;return}if(!inView||started.current)return;started.current=true;const timers=photos.map((_,i)=>setTimeout(()=>setLanded(i+1),600+i*850));return()=>timers.forEach(clearTimeout)},[inView,paused,reduce]);
 useEffect(()=>{if(!detail)return;const fn=e=>{if(e.key==='Escape'){setDetail(null);opener.current?.focus()}if(e.key==='Tab'){const items=[...document.querySelector('.achievement-detail-overlay').querySelectorAll('button,a[href]')];const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',fn);return()=>document.removeEventListener('keydown',fn)},[detail]);
 return <div ref={box} className={'achievement-collage '+(reduce||paused?'collage-static':'')+(inView?' collage-playing':'')}><div className="collage-terminal" aria-hidden="true"><span>A FEW MOMENTS, ALL TOGETHER.</span><p>Tap a photograph to take a closer look.</p></div><div className="polaroid-stage">{photos.map((p,i)=><a key={p.label} className={'achievement-polaroid '+(i<landed?'has-landed':'')} style={{'--rotation':(placements[i]?.r||0)+'deg','--x':(placements[i]?.x||50)+'%','--y':(placements[i]?.y||50)+'%','--stack':i+2}} href={p.src} onClick={e=>{e.preventDefault();opener.current=e.currentTarget;setDetail(p)}} aria-label={'Open '+p.label} aria-hidden={i>=landed} tabIndex={i<landed?0:-1}><img src={p.src} alt={p.label}/><span>{p.label}</span></a>)}</div><div className="collage-browse" aria-label="Browse every photograph">{photos.map((p,i)=><button key={p.label} aria-label={'Open '+p.label} onClick={e=>{opener.current=e.currentTarget;setDetail(p)}}>{String(i+1).padStart(2,'0')}</button>)}</div>{detail&&createPortal(<div className="achievement-detail-overlay" onClick={()=>{setDetail(null);opener.current?.focus()}}><section role="dialog" aria-modal="true" aria-label={detail.label} onClick={e=>e.stopPropagation()}><button autoFocus className="achievement-close" onClick={()=>{setDetail(null);opener.current?.focus()}}>Close ×</button><h3>{detail.label}</h3><img src={detail.src} alt={detail.label}/><div><a href={detail.src} target="_blank" rel="noreferrer">Open full image ↗</a>{detail.link&&<a href={detail.link} target="_blank" rel="noreferrer">{detail.linkLabel} ↗</a>}</div><p>{detail.link?"Matched event link.":"Original photograph from my personal archive."}</p></section></div>,document.body)}</div>
}
