'use client';
import {createPortal} from 'react-dom';
import React,{useEffect,useRef,useState} from 'react';
const defaultAssets={module:'/hand-control/vision_bundle.mjs',loader:'/hand-control/vision_wasm_internal.js',wasm:'/hand-control/vision_wasm_internal.wasm',loaderNo:'/hand-control/vision_wasm_nosimd_internal.js',wasmNo:'/hand-control/vision_wasm_nosimd_internal.wasm',model:'/hand-control/hand_landmarker.task'};
import PaperHand from './PaperHand';
const edges=[[0,1,2,3,4],[0,5,6,7,8],[5,9,10,11,12],[9,13,14,15,16],[13,17,18,19,20],[0,17]];
export default function HandControl({assets=defaultAssets,workerSource=null}){
 const[mounted,setMounted]=useState(false);useEffect(()=>setMounted(true),[]);const[panel,setPanel]=useState(false),[status,setStatus]=useState('off'),[message,setMessage]=useState(''),[hand,setHand]=useState(null),[cursor,setCursor]=useState(null),[mode,setMode]=useState('Show one hand');
 const runtime=useRef({epoch:0}),container=useRef(null);
 const stop=(text='Camera off.')=>{const r=runtime.current;r.epoch++;clearTimeout(r.timeout);cancelAnimationFrame(r.raf);r.stream?.getTracks().forEach(t=>t.stop());r.video?.pause();if(r.video)r.video.srcObject=null;r.worker?.terminate();if(r.blob)URL.revokeObjectURL(r.blob);Object.assign(r,{worker:null,stream:null,video:null,raf:0,busy:false});setStatus('off');setHand(null);setCursor(null);setMessage(text)};
 useEffect(()=>{const hide=()=>{if(document.hidden)stop('Camera stopped when this tab was hidden. Enable again to continue.')};const key=e=>{if(e.key==='Escape')stop()};document.addEventListener('visibilitychange',hide);document.addEventListener('keydown',key);return()=>{document.removeEventListener('visibilitychange',hide);document.removeEventListener('keydown',key);const r=runtime.current;r.epoch++;r.stream?.getTracks().forEach(t=>t.stop());r.worker?.terminate();cancelAnimationFrame(r.raf);clearTimeout(r.timeout);if(r.blob)URL.revokeObjectURL(r.blob)}},[]);
 const start=async()=>{if(status!=='off')return;setPanel(true);if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia||!window.Worker||!window.createImageBitmap){setMessage('Hand control needs HTTPS and a supported browser. Touch, mouse and keyboard still work.');return}const r=runtime.current;const epoch=++r.epoch;setStatus('loading');setMessage('Asking for camera permission. Nothing is recorded or uploaded.');try{const stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:'user',width:{ideal:480},height:{ideal:360},frameRate:{ideal:15,max:20}}});if(r.epoch!==epoch){stream.getTracks().forEach(t=>t.stop());return}r.stream=stream;const video=document.createElement('video');video.muted=true;video.playsInline=true;video.srcObject=stream;r.video=video;await video.play();if(r.epoch!==epoch)return;setMessage('Loading local hand tracking. The first start can take a moment.');const url=workerSource?(r.blob=URL.createObjectURL(new Blob([workerSource],{type:'text/javascript'}))):'/hand-control/worker.js';const worker=new Worker(url);r.worker=worker;r.lastHand=performance.now();r.acquiredAt=0;r.detected=false;r.interval=100;r.pinch=false;r.clickAt=0;r.smooth=null;r.lastFrame=0;
 const root=container.current.closest('.portfolio');
 worker.onmessage=e=>{if(r.epoch!==epoch)return;const m=e.data;if(m.type==='error'){stop(m.message+' Use touch, mouse or keyboard.');return}if(m.type==='ready'){clearTimeout(r.timeout);setStatus('on');setPanel(false);setMessage('Tracking locally. Escape or Turn off stops the camera.');tick();return}if(m.type!=='result')return;r.busy=false;r.interval=Math.max(85,Math.min(250,m.ms*1.6));const now=performance.now(),h=m.hand;if(!h){if(now-r.lastHand>800){setHand(null);setCursor(null);r.pinch=false;r.smooth=null;r.detected=false;setMode('Show one hand')}return}r.lastHand=now;if(!r.detected){r.detected=true;r.acquiredAt=now}setHand(h);if(root.querySelector('.hand-control-panel')){setCursor(null);r.pinch=false;return}const palm=Math.hypot(h[0].x-h[9].x,h[0].y-h[9].y);const pinch=Math.hypot(h[4].x-h[8].x,h[4].y-h[8].y)<palm*.3;const extended=[8,12,16,20].filter(i=>Math.hypot(h[i].x-h[0].x,h[i].y-h[0].y)>Math.hypot(h[i-2].x-h[0].x,h[i-2].y-h[0].y)*1.13).length;
 if(extended>=4&&!pinch){r.pinch=false;setCursor(null);setMode('Open palm: scroll');const dy=h[9].y-.5;if(Math.abs(dy)>.12){const delta=(dy-Math.sign(dy)*.12)*120;const dialog=root.querySelector('.project-dialog');if(dialog)dialog.scrollTop+=delta;else if(root.scrollHeight>root.clientHeight+2&&['auto','scroll'].includes(getComputedStyle(root).overflowY))root.scrollTop+=delta;else window.scrollBy({top:delta,behavior:'instant'})}return}
 const raw={x:(1-h[8].x)*innerWidth,y:h[8].y*innerHeight};const c=r.smooth?{x:r.smooth.x*.6+raw.x*.4,y:r.smooth.y*.6+raw.y*.4}:raw;r.smooth=c;setCursor({...c,pinch});setMode('Point: move cursor. Pinch: click');if(pinch&&!r.pinch&&now-r.clickAt>1000&&now-r.acquiredAt>950){r.clickAt=now;const target=document.elementFromPoint(c.x,c.y)?.closest('button,a');if(target&&root.contains(target)&&!target.disabled&&!target.closest('.hand-control-panel')&&!target.matches('[data-no-gesture]')&&(!target.href||new URL(target.href).origin===location.origin)){target.focus();target.click()}}r.pinch=pinch;
 };
 const tick=async()=>{if(r.epoch!==epoch)return;const now=performance.now();if(now-r.lastHand>60000){stop('Camera stopped after one minute without a hand.');return}if(!r.busy&&now-r.lastFrame>r.interval&&video.readyState>=2){r.busy=true;r.lastFrame=now;try{const bitmap=await createImageBitmap(video);if(r.epoch!==epoch){bitmap.close();return}worker.postMessage({type:'frame',bitmap,time:now},[bitmap])}catch{stop('Camera frames unavailable. Use touch, mouse or keyboard.');return}}r.raf=requestAnimationFrame(tick)};
 r.timeout=setTimeout(()=>{if(r.epoch===epoch)stop('Hand tracking took too long to load. Camera stopped. Try again or use normal controls.')},45000);
 worker.onerror=()=>stop('Hand tracking unavailable on this browser. Normal controls still work.');worker.postMessage({type:'init',assets:Object.fromEntries(Object.entries(assets).map(([k,v])=>[k,new URL(v,location.href).href]))});
 }catch(err){if(r.epoch===epoch)stop(err.name==='NotAllowedError'?'Camera permission was not granted. Nothing is running. Normal controls still work.':err.name==='NotFoundError'?'No camera found. Normal controls still work.':'Could not start camera. Normal controls still work.')}};
 useEffect(()=>{const open=()=>{setPanel(true);start()};window.addEventListener('portfolio-enable-hand',open);return()=>window.removeEventListener('portfolio-enable-hand',open)},[status]);

 return <div className="hand-control" ref={container}>{mounted&&createPortal(<>{status!=='off'&&<button className="hand-camera-off" data-no-gesture onClick={()=>stop()}>Turn off camera</button>}<button className={'hand-control-open '+(status==='on'?'is-on':'')} data-no-gesture onClick={()=>status==='off'?start():setPanel(!panel)} aria-label="Hand control" title="Optional camera hand control. Video stays on your device." aria-expanded={panel}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 13V6a1.5 1.5 0 0 1 3 0v5-7a1.5 1.5 0 0 1 3 0v7-5a1.5 1.5 0 0 1 3 0v6-3a1.5 1.5 0 0 1 3 0v7c0 4-2 6-6 6h-1c-2 0-3-1-4-3l-4-5a1.5 1.5 0 0 1 2-2z"/><path d="M3 6a5 5 0 0 1 5-5"/></svg><span className="hand-side-label">{status==='on'?'On':'Hand control'}</span></button>{panel&&<aside className="hand-control-panel" aria-label="Optional hand control"><strong>Move through the work, by hand.</strong><p>Optional camera control using MediaPipe, not OpenCV. Video stays on your device. Nothing is recorded, stored or sent.</p><p>Point one finger to move the cursor. Pinch thumb and index to click page controls. Open palm above or below the centre to scroll. External links need a normal tap.</p><small>Loads about 18 MB only when enabled. Best tried on desktop; phone speed varies.</small><div className="hand-control-actions"><button data-no-gesture onClick={status==='off'?start:()=>stop()}>{status==='off'?'Enable hand control':status==='loading'?'Cancel / turn off':'Turn off camera'}</button><button data-no-gesture onClick={()=>setPanel(false)}>Close panel</button></div><p className="hand-control-status" role="status">{message||'Camera is off. No camera access until you enable.'}{status==='on'&&<span>{mode}</span>}</p></aside>}</>,document.body)}<PaperHand hand={hand} cursor={cursor} pinch={cursor?.pinch}/></div>
}
