'use client';
import React,{useEffect,useRef,useState} from 'react';
export default function HeroWalk({src,poster,fallback}){
 const el=useRef(null);const [playing,setPlaying]=useState(false),[blocked,setBlocked]=useState(false);
 useEffect(()=>{const v=el.current;if(!v)return;const mq=matchMedia('(prefers-reduced-motion:reduce)');let inView=true,lastTime=-1,lastAdvance=performance.now(),frameId=0;const mark=()=>{if(mq.matches)return;setPlaying(true);setBlocked(false);lastAdvance=performance.now()};const hide=()=>setPlaying(false);const attempt=()=>{if(mq.matches||document.hidden||!inView){v.pause();hide();return;}v.muted=true;v.defaultMuted=true;v.playsInline=true;const p=v.play();p?.then(()=>{if(v.requestVideoFrameCallback){frameId=v.requestVideoFrameCallback(mark)}else if(v.readyState>=2)mark()}).catch(()=>{hide();setBlocked(true)})};const scroll=()=>{if(inView&&!mq.matches&&!document.hidden){if(v.paused)attempt();if(v.paused&&v.readyState>=2&&Number.isFinite(v.duration)&&v.duration>0){const h=v.closest('.sketch-hero').getBoundingClientRect();v.currentTime=Math.min(v.duration-.1,Math.max(0,-h.top/h.height)*v.duration)}}};const stall=()=>{hide();setBlocked(true)};const obs=new IntersectionObserver(es=>{inView=es[0]?.isIntersecting??false;if(inView)attempt();else v.pause()},{threshold:.01});obs.observe(v);v.addEventListener('canplay',attempt);v.addEventListener('playing',mark);v.addEventListener('waiting',hide);v.addEventListener('stalled',stall);v.addEventListener('error',stall);document.addEventListener('visibilitychange',attempt);window.addEventListener('pageshow',attempt);window.addEventListener('touchstart',attempt,{passive:true});window.addEventListener('pointerdown',attempt,{passive:true});window.addEventListener('scroll',scroll,{passive:true});mq.addEventListener('change',attempt);
 const timer=setInterval(()=>{if(!inView||document.hidden||mq.matches)return;if(v.currentTime!==lastTime){lastTime=v.currentTime;lastAdvance=performance.now()}else if(performance.now()-lastAdvance>2500){stall();attempt()}},1500);attempt();return()=>{clearInterval(timer);obs.disconnect();if(frameId&&v.cancelVideoFrameCallback)v.cancelVideoFrameCallback(frameId);v.removeEventListener('canplay',attempt);v.removeEventListener('playing',mark);v.removeEventListener('waiting',hide);v.removeEventListener('stalled',stall);v.removeEventListener('error',stall);document.removeEventListener('visibilitychange',attempt);window.removeEventListener('pageshow',attempt);window.removeEventListener('touchstart',attempt);window.removeEventListener('pointerdown',attempt);window.removeEventListener('scroll',scroll);mq.removeEventListener('change',attempt)};
 },[src]);
 return <><img className="hero-walk-backup" src={fallback} alt="Vignesh walking in a purple blazer"/><video className={'hero-walk-video '+(playing?'is-playing':'')} ref={el} src={src} poster={poster} autoPlay muted loop playsInline preload="auto" aria-label="Vignesh walking in a purple blazer"/><img className="hero-walk-still" src={poster} alt="Vignesh in a purple blazer"/>{blocked&&<button className="hero-walk-play" onClick={()=>{const v=el.current;v.muted=true;v.play().catch(()=>{});}}>Play walk ↗</button>}</>
}
