'use client';
import {useEffect,useRef,useState} from 'react';
export default function Observatory({figure,paused,onReady}){
 const mount=useRef(null);const [eligible,setEligible]=useState(false);useEffect(()=>{const wide=matchMedia('(min-width:821px)'),reduce=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setEligible(wide.matches&&!reduce.matches);sync();wide.addEventListener('change',sync);reduce.addEventListener('change',sync);return()=>{wide.removeEventListener('change',sync);reduce.removeEventListener('change',sync)};},[]);
 useEffect(()=>{const host=mount.current;if(!host||paused||!eligible){onReady?.(false);return;}let stopped=false,cleanup=()=>{};
 import('three').then(T=>{if(stopped)return;let renderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});}catch{return;}renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.setClearColor(0xf5f1e5,1);renderer.outputColorSpace=T.SRGBColorSpace;host.appendChild(renderer.domElement);
 const scene=new T.Scene();scene.fog=new T.FogExp2(0xf5f1e5,.008);const camera=new T.PerspectiveCamera(48,1,.1,160);const ambient=new T.AmbientLight(0xbedee8,2);scene.add(ambient);const cyan=new T.PointLight(0x31e2f0,60,35);cyan.position.set(0,6,4);scene.add(cyan);const amber=new T.PointLight(0xf4b260,30,20);amber.position.set(-6,2,3);scene.add(amber);
 const materials=[],geometries=[],textures=[];const mesh=(geo,mat)=>{geometries.push(geo);materials.push(mat);return new T.Mesh(geo,mat)};
 const floor=mesh(new T.PlaneGeometry(160,160),new T.MeshBasicMaterial({color:0xe7e1d2}));floor.rotation.x=-Math.PI/2;floor.position.y=-3.7;scene.add(floor);
 const grid=new T.GridHelper(160,80,0x9b957f,0xd3cdbc);grid.position.y=-3.69;scene.add(grid);
 let dirty=true;const loader=new T.TextureLoader();const load=url=>{const t=loader.load(url,()=>{dirty=true});t.colorSpace=T.SRGBColorSpace;textures.push(t);return t};
 const screens=[];const names=['OUTSURANCE','GARUDA','SPARSH MUKTHI','NAVIMEET','GYANEDGE','TIZ-GUN'];const urls=['/assets/outsurance-live.png','/assets/garuda-live.png',null,'/assets/navimeet.jpg','/assets/gyanedge-live.png','/assets/tizgun-live.png'];
 function label(text,w=1024,h=96){const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d');x.fillStyle='#25261f';x.fillRect(0,0,w,h);x.fillStyle='#f8f3e8';x.font='28px monospace';x.fillText(text,24,59);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;textures.push(t);return t;}
 const accents=[0xb5a1cf,0xc6c99c,0xe4bd95,0xb5a1cf,0xc6c99c,0xe4bd95];
 for(let i=0;i<6;i++){const g=new T.Group();g.position.set((i%2?1:-1)*7,1,-i*13);g.rotation.y=i%2?-.23:.23;
 const shadow=mesh(new T.BoxGeometry(10.5,6.5,.08),new T.MeshBasicMaterial({color:accents[i]}));shadow.position.set(.16,-.16,-.13);g.add(shadow);
 const glass=mesh(new T.BoxGeometry(10.35,6.35,.12),new T.MeshBasicMaterial({color:0xfffcf4}));g.add(glass);
 const edgeGeo=new T.EdgesGeometry(glass.geometry),edgeMat=new T.LineBasicMaterial({color:0x25261f,transparent:true,opacity:.9});geometries.push(edgeGeo);materials.push(edgeMat);const edge=new T.LineSegments(edgeGeo,edgeMat);g.add(edge);
 const image=urls[i]?load(urls[i]):(()=>{const c=document.createElement('canvas');c.width=1024;c.height=576;const x=c.getContext('2d');x.fillStyle='#f5edcc';x.fillRect(0,0,1024,576);x.fillStyle='#25261f';x.font='bold 74px sans-serif';x.fillText('Sparsh Mukthi',70,170);x.fillStyle='#765ab6';x.font='34px monospace';x.fillText('VOICE / 3D CLASSROOM / AI',70,250);x.strokeStyle='#25261f';x.lineWidth=4;x.strokeRect(70,320,270,130);x.beginPath();x.moveTo(100,375);x.lineTo(130,350);x.lineTo(170,410);x.lineTo(210,345);x.lineTo(280,390);x.stroke();x.font='24px monospace';x.fillText('Project title card',440,400);const t=new T.CanvasTexture(c);t.colorSpace=T.SRGBColorSpace;textures.push(t);return t;})();const panel=mesh(new T.PlaneGeometry(9.8,5.5),new T.MeshBasicMaterial({map:image,transparent:false,opacity:1}));panel.position.z=.08;g.add(panel);
 const title=mesh(new T.PlaneGeometry(10,.75),new T.MeshBasicMaterial({map:label('SYS.0'+(i+1)+' / '+names[i]),transparent:true}));title.position.set(0,3.1,.1);g.add(title);
 const tape=mesh(new T.PlaneGeometry(1.9,.48),new T.MeshBasicMaterial({color:0xf2d96d,transparent:true,opacity:.72}));tape.position.set(3.6,3.43,.17);tape.rotation.z=.13;g.add(tape);
 const support=mesh(new T.CylinderGeometry(.025,.025,8,6),new T.MeshBasicMaterial({color:0x9b957f,transparent:true,opacity:.4}));support.position.set(0,-4,0);g.add(support);
 const ring=mesh(new T.TorusGeometry(5.6,.018,6,100),new T.MeshBasicMaterial({color:0x765ab6,transparent:true,opacity:.4}));ring.rotation.x=-Math.PI/2;ring.position.y=-4.6;g.add(ring);scene.add(g);screens.push(g);}
 const person=mesh(new T.PlaneGeometry(2.2,5.1),new T.MeshBasicMaterial({map:load(figure),transparent:true,depthWrite:false,side:T.DoubleSide}));person.position.set(0,-1,6);scene.add(person);
 const architecture=new T.Group();for(let i=0;i<8;i++){const portal=mesh(new T.TorusGeometry(15,.035,6,100),new T.MeshBasicMaterial({color:0xb1a3cc,transparent:true,opacity:.35}));portal.position.set(0,4,-i*13);architecture.add(portal);}scene.add(architecture);
 const starGeo=new T.BufferGeometry();const points=[];for(let i=0;i<450;i++)points.push((Math.random()-.5)*90,Math.random()*30-3,-Math.random()*110);starGeo.setAttribute('position',new T.Float32BufferAttribute(points,3));geometries.push(starGeo);const starMat=new T.PointsMaterial({color:0x8a7caa,size:.045,transparent:true,opacity:.65});materials.push(starMat);scene.add(new T.Points(starGeo,starMat));
 let raf=0,last=0,current=0;const cam=new T.Vector3(),target=new T.Vector3();function resize(){dirty=true;const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}resize();let contextLost=false;const lost=e=>{e.preventDefault();contextLost=true;onReady?.(false);};renderer.domElement.addEventListener('webglcontextlost',lost);const ro=new ResizeObserver(resize);ro.observe(host);
 function frame(time){raf=requestAnimationFrame(frame);if(contextLost||document.hidden||time-last<30)return;const bounds=host.getBoundingClientRect();if(bounds.bottom<0||bounds.top>innerHeight)return;last=time;const wall=host.closest('.room-scroll');const p=Number(wall?.style.getPropertyValue('--progress')||0);if(!dirty&&Math.abs(p-current)<.0002)return;dirty=false;current+=(p-current)*.28;const entry=Math.min(1,current/.19);const beat=Math.max(0,(current-.2)/.8)*5;const copy=wall?.querySelector('.chapter-copy');const chapter=Math.min(5,Math.round(beat));if(copy){const titles=['Outsurance','GARUDA','Sparsh Mukthi','NaviMeet','GyanEdge website','Tiz-Gun'];const descriptions=['Turns medical history into a risk tier and five ranked insurance plans, with an explanation of the decision.','Detects road damage and safety signals from camera feeds. Sends compact results instead of heavy video.','A voice-driven 3D classroom. Students can interrupt the AI teacher, ask questions and raise a hand naturally.','Find a meeting point for a group, with Google Maps and Vertex AI.','A responsive coaching website for courses and student enquiries.','A browser typing shooter game.'];copy.querySelector('h3').textContent=titles[chapter];copy.querySelector('p').textContent=descriptions[chapter];copy.querySelector('small').textContent=String(chapter+1).padStart(2,'0')+' / 06';copy.style.opacity=current<.18?0:1;wall.querySelectorAll('.chapter-dots i').forEach((d,i)=>d.classList.toggle('active',i===chapter));}const index=Math.min(5,Math.floor(beat));const raw=Math.max(0,Math.min(1,(beat-index-.42)/.16));const f=raw*raw*(3-2*raw);const a=screens[index].position,b=screens[Math.min(5,index+1)].position;
 const focusX=T.MathUtils.lerp(a.x,b.x,f),focusZ=T.MathUtils.lerp(a.z,b.z,f);cam.set(focusX-5.8,1.2,focusZ+13);target.set(focusX-1,1,focusZ);camera.position.set(T.MathUtils.lerp(0,cam.x,entry),T.MathUtils.lerp(1.5,cam.y,entry),T.MathUtils.lerp(25,cam.z,entry));camera.lookAt(T.MathUtils.lerp(0,target.x,entry),1,T.MathUtils.lerp(-13,target.z,entry));person.material.opacity=Math.max(0,1-current*5.5);screens.forEach((g,i)=>{g.visible=current<.2||Math.abs(beat-i)<.64;g.children.forEach(child=>{if(child.material&&i!==Math.round(beat)&&current>.2){child.material.transparent=true;child.material.opacity=.08;}else if(child.material){child.material.opacity=1;}});});person.visible=current<.2;renderer.render(scene,camera);}
 onReady?.(true);raf=requestAnimationFrame(frame);cleanup=()=>{cancelAnimationFrame(raf);ro.disconnect();renderer.domElement.removeEventListener('webglcontextlost',lost);grid.geometry.dispose();grid.material.dispose();geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.dispose();renderer.domElement.remove();onReady?.(false);};}).catch(()=>{});return()=>{stopped=true;cleanup();};},[figure,paused,eligible]);
 return <div className="observatory-canvas" ref={mount} aria-hidden="true"/>;
}
