'use client';
import AchievementArchive,{AchievementHome} from './AchievementArchive';
import SiteMenu from './SiteMenu';
import WorkExperience from './WorkExperience';
import ProjectGallery from './ProjectGallery';
import AchievementCollage from './AchievementCollage';
import React,{useState,useEffect,useRef} from 'react';


const award0='/assets/achievements/award0.jpeg';
const award3='/assets/achievements/award3.jpeg';
const award3cert='/assets/achievements/award3cert.pdf';
const learn0='/assets/achievements/learn0.pdf';
const learn1='/assets/achievements/learn1.jpeg';
const learn2='/assets/achievements/learn2.jpg';
const learn3='/assets/achievements/learn3.jpeg';
const learn4='/assets/achievements/learn4.png';
const learn5='/assets/achievements/learn5.jpeg';
const learn6='/assets/achievements/learn6.pdf';
const learn7='/assets/achievements/learn7.pdf';
const learn8='/assets/achievements/learn8.pdf';
const award3certpreview='/assets/achievements/award3certpreview.jpg';
const learn0preview='/assets/achievements/learn0preview.jpg';
const learn6preview='/assets/achievements/learn6preview.jpg';
const learn7preview='/assets/achievements/learn7preview.jpg';
const learn8preview='/assets/achievements/learn8preview.jpg';
const moment2='/assets/achievements/moment2.jpg';
const moment3='/assets/achievements/moment3.jpg';
const moment5='/assets/achievements/moment5.jpg';
const moment7='/assets/achievements/moment7.jpg';
const moment9='/assets/achievements/moment9.jpg';
const moment10='/assets/achievements/moment10.jpg';
const moment12='/assets/achievements/moment12.jpg';
const moment14='/assets/achievements/moment14.jpg';
const moment18='/assets/achievements/moment18.jpg';
const fidelityAward='/assets/achievements/fidelity.jpg';
const moments=[moment2,moment3,moment5,moment7,moment9,moment10,moment12,moment14,moment18];
const collage1='/assets/achievements/collage1.jpg';
const collage6='/assets/achievements/collage6.jpg';
const collage12='/assets/achievements/collage12.jpg';
const collage18='/assets/achievements/collage18.jpg';
const projects=[
 {id:'outsurance',title:'Outsurance',category:'01 / APPLIED MACHINE LEARNING',line:"AI Health Insurance Advisor",description:"A local LLM (Gemma 3) reads unstructured medical history and scores severity, replacing hardcoded rules. That score became the top feature (24% importance) in an XGBoost risk classifier (4 tiers, 85% F1, SHAP explanations). A Cosine-KNN ranker then returns the top 5 plans.",resumeBullets:["A local LLM (Gemma 3) reads unstructured medical history and scores severity, replacing hardcoded rules.", "That score became the top feature (24% importance) in an XGBoost risk classifier (4 tiers, 85% F1, SHAP explanations). A Cosine-KNN ranker then returns the top 5 plans."],metric:'85%',unit:'classifier F1',stack:['Gemma 3','XGBoost','SHAP','Cosine-KNN'],steps:['Medical history','Local LLM','Risk model','Plan ranking'],details:["A local LLM (Gemma 3) reads unstructured medical history and scores severity, replacing hardcoded rules.", "That score became the top feature (24% importance) in an XGBoost risk classifier (4 tiers, 85% F1, SHAP explanations). A Cosine-KNN ranker then returns the top 5 plans."],url:'https://outsurance.vercel.app/',code:'https://github.com/vigneshbs33/outsurance'},
 {id:'garuda',title:'GARUDA',category:'02 / EDGE COMPUTER VISION',line:"Edge AI for Road Safety",description:"Fine-tuned YOLOv12s on RDD2022 (5 road-damage classes) and built a Damage Severity Score. Regression over past scores forecasts when a road will fail. Runs on the edge over existing CCTV and dashcam feeds and sends about 2 KB of JSON instead of video, cutting bandwidth by 99%. Also added YOLO11 with ByteTrack, EasyOCR plate reading and MediaPipe drowsiness detection.",resumeBullets:["Fine-tuned YOLOv12s on RDD2022 (5 road-damage classes) and built a Damage Severity Score. Regression over past scores forecasts when a road will fail.", "Runs on the edge over existing CCTV and dashcam feeds and sends about 2 KB of JSON instead of video, cutting bandwidth by 99%. Also added YOLO11 with ByteTrack, EasyOCR plate reading and MediaPipe drowsiness detection."],metric:'99%',unit:'bandwidth reduction',stack:['YOLO','ByteTrack','EasyOCR','MediaPipe'],steps:['Camera feed','Edge inference','Severity score','Compact JSON'],details:["Fine-tuned YOLOv12s on RDD2022 (5 road-damage classes) and built a Damage Severity Score. Regression over past scores forecasts when a road will fail.", "Runs on the edge over existing CCTV and dashcam feeds and sends about 2 KB of JSON instead of video, cutting bandwidth by 99%. Also added YOLO11 with ByteTrack, EasyOCR plate reading and MediaPipe drowsiness detection."],url:'https://garuda-teal.vercel.app/',code:'https://github.com/vigneshbs33/garuda'},
 {id:'sparsh',title:'Sparsh Mukthi',category:'03 / MULTIMODAL AI',line:"Voice-Driven 3D AI Classroom",description:"Students can interrupt the AI teacher mid-lesson. Routes between Gemini, Claude and GPT-4o with strict JSON output. Serves Orpheus-TTS (3B) voices through FastAPI and runs MediaPipe in the browser for hand-raise and attention tracking.",resumeBullets:["Students can interrupt the AI teacher mid-lesson. Routes between Gemini, Claude and GPT-4o with strict JSON output.", "Serves Orpheus-TTS (3B) voices through FastAPI and runs MediaPipe in the browser for hand-raise and attention tracking."],metric:'3B',unit:'Orpheus-TTS voice model',stack:['Gemini','FastAPI','MediaPipe','Orpheus-TTS'],steps:['Student voice','Model routing','Structured lesson','Natural speech'],details:["Students can interrupt the AI teacher mid-lesson. Routes between Gemini, Claude and GPT-4o with strict JSON output.", "Serves Orpheus-TTS (3B) voices through FastAPI and runs MediaPipe in the browser for hand-raise and attention tracking."],url:'https://www.sparsh-mukthi.xyz/',code:'https://github.com/vigneshbs33/SP3D'}
];
const otherProjects=[
{id:'navimeet',title:'NaviMeet',description:'Find a meeting point for a group, with Google Maps and Vertex AI.',stack:['Google Maps','Vertex AI'],details:['A meeting-point finder using participant locations and group navigation. The image is from the original project archive.'],url:'https://navimeet.xyz/'},
{id:'gyanedge',title:'GyanEdge website',description:'A responsive coaching website for courses and student enquiries.',stack:['React','Full-stack'],details:['The coaching website from the original portfolio archive. It is separate from the assessment platform described in my experience.'],url:'https://gyanedge.co/'},
{id:'paraso',title:'Paraso',description:'Gesture and voice desktop automation.',stack:['Python','Agentic AI'],details:['Gesture recognition, voice commands and automation for desktop interaction.'],code:'https://github.com/vigneshbs33/Paraso-Agentic-AI-Control-System'},
{id:'mindmate',title:'MindMate',description:'A Flutter AI companion with conversational memory.',stack:['Flutter','AI'],details:['A mobile companion with context-aware conversation and memory, from the original portfolio project list.'],code:'https://github.com/vigneshbs33/mindmate'},
{id:'tizgun',title:'Tiz-Gun',description:'A browser typing shooter game.',stack:['JavaScript','Game'],details:['Typing-based gameplay with progressive difficulty, from the original portfolio project list.'],url:'https://tiz-gun.vercel.app/'}
];
const allProjects=[...projects,...otherProjects];
const experience=[['01','LessonPlan','AI Systems Developer','Nov 2025 - Present','AI features, RAG and model deployment.'],['02','GyanEdge','Lead Developer · Part-time','Mar 2025 - Present','Full-stack development and assessment workflows.'],['03','OpenIntervue','QA Engineer · Intern','May 2025 - Jul 2025','Automation and quality testing for an LLM interview product.']];
const skills=[['Models & perception','PyTorch / TensorFlow / XGBoost / YOLO / OpenCV'],['Automation & agents','API workflows / RAG / LLM integration / Agentic tool use'],['Product engineering','Next.js / React / TypeScript / FastAPI / Node.js'],['Production systems','Docker / CI/CD / PostgreSQL / REST APIs / Test automation']];
export default function Portfolio({portrait,resume,video,videoPoster,resumePreview,backFigure,embedded=false,view="home"}){
 const [threeReady,setThreeReady]=useState(false);const [selected,setSelected]=useState(0); const [page,setPage]=useState(view); const [story,setStory]=useState(0);const [workflow,setWorkflow]=useState(0);const [step,setStep]=useState(0);const [videoReady,setVideoReady]=useState(false);const [active,setActive]=useState(null),[menu,setMenu]=useState(false),[paused,setPaused]=useState(false);const root=useRef(null);
 useEffect(()=>{const r=root.current;if(!r||page!=='home')return;let frame=0;const update=()=>{frame=0;const hero=r.querySelector('.sketch-hero');if(!hero)return;const rect=hero.getBoundingClientRect();const reduced=paused||matchMedia('(prefers-reduced-motion: reduce)').matches;const raw=Math.max(0,Math.min(1,-rect.top/(rect.height*.82)));const p=reduced?(raw>.5?1:0):raw*raw*(3-2*raw);const c=[12,14,17].map((v,i)=>Math.round(v+([250,246,235][i]-v)*p));r.style.setProperty('--intro-bg',`rgb(${c.join(',')})`);r.style.setProperty('--intro-fg',p<.44?'#faf6eb':'#101214');r.style.setProperty('--intro-muted',p<.44?'#faf6eb':'#101214');r.style.setProperty('--intro-accent',p<.44?'#e0cef9':'#493367');r.style.setProperty('--intro-ink',p<.44?'#faf6eb':'#101214');r.dataset.introTheme=p<.44?'dark':'light';};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update)};addEventListener('scroll',scroll,{passive:true});addEventListener('resize',scroll);update();return()=>{removeEventListener('scroll',scroll);removeEventListener('resize',scroll);cancelAnimationFrame(frame)}},[page,paused]);
 useEffect(()=>{const r=root.current;if(!r)return;let obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('entered');obs.unobserve(e.target)}}),{threshold:.1});r.querySelectorAll('[data-reveal]').forEach(x=>obs.observe(x));return()=>obs.disconnect()},[page]);
 useEffect(()=>{if(!active)return;const prior=document.activeElement;const bodyOverflow=document.body.style.overflow;document.body.style.overflow="hidden";const dialog=root.current?.querySelector('[role=dialog]');const focus=Array.from(dialog?.querySelectorAll('button,a')||[]);focus[0]?.focus();const listener=e=>{if(e.key==='Escape')setActive(null);if(e.key==='Tab'&&focus.length){if(e.shiftKey&&document.activeElement===focus[0]){e.preventDefault();focus.at(-1).focus()}else if(!e.shiftKey&&document.activeElement===focus.at(-1)){e.preventDefault();focus[0].focus()}}};document.addEventListener('keydown',listener);return()=>{document.removeEventListener('keydown',listener);document.body.style.overflow=bodyOverflow;prior?.focus?.()}},[active]);
 useEffect(()=>{const v=root.current?.querySelector('video');if(!v)return;const mq=matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>{if(paused||mq.matches)v.pause();else v.play().catch(()=>{})};sync();mq.addEventListener('change',sync);return()=>mq.removeEventListener('change',sync)},[paused]);
 const go=()=>setMenu(false);
 const navigate=(e,name)=>{setMenu(false);if(embedded){e.preventDefault();setPage(name);root.current?.scrollTo({top:0,behavior:'instant'});}};
 const footer=<section id="contact" className="contact-section"><span className="eyebrow">HAVE SOMETHING IN MIND?</span><h2>Let's make<br/><em>it work.</em></h2><a className="contact-email" href="mailto:vignesh.bs06@gmail.com">vignesh.bs06@gmail.com <span>↗</span></a><div className="contact-links"><a href="https://github.com/vigneshbs33" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://linkedin.com/in/vigneshbs-dev" target="_blank" rel="noreferrer">LinkedIn ↗</a><a href="/resume" onClick={e=>navigate(e,'resume')}>Resume ↗</a><a href="/contact" onClick={e=>navigate(e,'contact')}>Contact page ↗</a></div><footer><span>Vignesh B S</span><span>Bengaluru · AI & automation</span><span>{embedded?'Private review':'© 2026'}</span></footer></section>;

 return <div className={'portfolio '+(videoReady?'video-ready ':'')+(paused?'motion-off':'')} ref={root}>
 <a className="skip" href="#selected-work">Skip to projects</a>
 <header className="site-nav"><a href="/" onClick={e=>navigate(e,'home')} className="wordmark" aria-label="Vignesh home">Vignesh B S<span>✳</span></a><nav aria-label="Portfolio navigation" className="desktop-site-nav"><a href={page==='home'?'#selected-work':'/#selected-work'} onClick={e=>{if(page!=='home'&&embedded){navigate(e,'home');setTimeout(()=>root.current?.querySelector('#selected-work')?.scrollIntoView({behavior:'smooth'}),50)}else go()}}>Projects</a><a href={page==='home'?'#experience':'/#experience'} onClick={e=>{if(page!=='home'&&embedded){navigate(e,'home');setTimeout(()=>root.current?.querySelector('#experience')?.scrollIntoView({behavior:'smooth'}),50)}else go()}}>Experience</a><a href="/achievements" onClick={e=>navigate(e,'achievements')}>Achievements</a><a href="/contact" onClick={e=>navigate(e,'contact')}>Contact</a></nav><a className="nav-resume" href="/resume" onClick={e=>navigate(e,'resume')}>Resume <span>↗</span></a><button className="menu-toggle" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label="Open menu">Menu</button></header>
 {page==='home'&&<>
 <section id="intro" className="hero sketch-hero"><div className="hero-top"><span><i/> Bengaluru, India</span><span>AI / AUTOMATION / PRODUCTS</span></div><div className="sketch-grid" aria-hidden="true"/><span className="sketch-sticker sticker-one" aria-hidden="true">less busywork ✳</span><span className="sketch-sticker sticker-two" aria-hidden="true">built, not just imagined.</span><div className="hero-portrait walking-frame"><span className="frame-tape" aria-hidden="true"/>{video&&(embedded?<img className="walking-animation" src={video} alt="Vignesh walking in a purple blazer" onLoad={()=>setVideoReady(true)}/>:<video src={video} poster={videoPoster||portrait} autoPlay muted loop playsInline preload="metadata" onLoadedData={()=>setVideoReady(true)} aria-label="Vignesh walking in a purple blazer"/>)}<img className="walk-fallback" src={portrait} alt="Vignesh in a purple blazer"/><span className="walk-caption">Vignesh, in motion. ↗</span></div><svg className="hero-doodle" viewBox="0 0 420 250" fill="none" aria-hidden="true"><path d="M17 32Q85 5 115 54T177 48M164 37l14 11-18 10M18 145l55 9 12 66-60-4zM31 160l26 4M97 185l38-8 13 39-49 8zM267 23l13 26 30 2-23 18 9 29-26-17-25 18 7-30-23-18 30-3zM303 143q80-7 70 45q-7 36-65 29M310 206l-4 13 14 7" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg><div className="hero-title"><h1 className="hero-full-name">Vignesh B S</h1><p className="hero-statement">I make <em>AI useful.</em></p><p className="hero-summary">Less busywork. More possibility.<br/>AI systems, automation and the products around them.</p><a className="primary-button" href="#selected-work">See what I've built <span>↘</span></a><a className="hero-secondary" href="/contact" onClick={e=>navigate(e,'contact')}>Say hello ↗</a></div><div className="hero-bottom"><span>Turn the page ↓</span></div></section>
<div className="hero-social-links"><span className="eyebrow">FIND ME ONLINE</span><a href="https://github.com/vigneshbs33" target="_blank" rel="noreferrer"><span>GitHub</span><small>Code & projects</small><i>↗</i></a><a href="https://linkedin.com/in/vigneshbs-dev" target="_blank" rel="noreferrer"><span>LinkedIn</span><small>Experience & updates</small><i>↗</i></a></div>
<WorkExperience/>
<section id="achievements" className="home-achievements" data-reveal><AchievementHome assets={{fidelity:fidelityAward,aventusPhoto:collage1,aventusCert:award0,academiaPhoto:collage6,academiaProof:award3,learn0,learn1,learn2,learn3,learn4,learn5,learn6,learn7,learn8,learn0preview,learn1preview:learn1,learn2preview:learn2,learn3preview:learn3,learn4preview:learn4,learn5preview:learn5,learn6preview,learn7preview,learn8preview}} openArchive={e=>navigate(e,'achievements')}/><AchievementCollage paused={paused} photos={[{src:fidelityAward,label:'Fidelity India Hackathon 2026 · Award photograph'},{src:collage1,label:'Aventus 3.0 · Winner photograph',link:'https://devfolio.co/projects/sparsh-mukthi-5a19',linkLabel:'Aventus Grand Prize'},{src:moment2,label:'Aventus 3.0 · Team photograph',link:'https://devfolio.co/projects/sparsh-mukthi-5a19',linkLabel:'Aventus Grand Prize'},{src:moment18,label:'Aventus 3.0 · Prize photograph',link:'https://devfolio.co/projects/sparsh-mukthi-5a19',linkLabel:'Aventus Grand Prize'},{src:collage6,label:'Hack Academia · Runner-up photograph',link:'https://www.linkedin.com/posts/vigneshbs-dev_hackademia-hackwithindia-hackathon-activity-7366155378897661952-HsNE',linkLabel:'Hack Academia result'},{src:moment3,label:'Trophy photograph · Personal archive'},{src:moment5,label:'Campus photograph · Personal archive'},{src:moment7,label:'Event photograph · Personal archive'},{src:moment9,label:'Team photograph · Personal archive'},{src:moment10,label:'Presentation photograph · Personal archive'},{src:moment14,label:'Trophy photograph · Personal archive'},{src:moment12,label:'Campus photograph · Personal archive'},{src:award0,label:'Aventus 3.0 · Winner certificate'},{src:award3,label:'Hack Academia · Runner-up evidence'}]}/></section>
<ProjectGallery projects={projects} images={{outsurance:'/assets/outsurance-live.png',garuda:'/assets/garuda-live.png',navimeet:'/assets/navimeet.jpg',gyanedge:'/assets/gyanedge-live.png',tizgun:'/assets/tizgun-live.png'}} onOpen={setActive}/>
 </>}
{page==='achievements'&&<AchievementArchive assets={{fidelity:fidelityAward,aventusPhoto:collage1,aventusCert:award0,academiaPhoto:collage6,academiaProof:award3,learn0,learn1,learn2,learn3,learn4,learn5,learn6,learn7,learn8,learn0preview,learn1preview:learn1,learn2preview:learn2,learn3preview:learn3,learn4preview:learn4,learn5preview:learn5,learn6preview,learn7preview,learn8preview}} back={e=>navigate(e,'home')}/>}
 {page==='resume'&&<section className="resume-page"><a className="back-link" href="/" onClick={e=>navigate(e,'home')}>← Back to projects</a><div className="page-heading"><span className="eyebrow">RESUME / VIGNESH B S</span><h1>The short<br/><em>version.</em></h1><p>AI and automation, from model to interface.</p><a className="primary-button" href={resume||'#'} download="Vignesh-B-S-Resume.pdf">Download resume <span>↓</span></a></div><div className="resume-summary"><article><span>FOCUS</span><h2>AI + automation</h2><p>Machine learning, agents, computer vision and full-stack products.</p></article><article><span>EXPERIENCE</span><h2>Building since 2025</h2><p>LessonPlan · GyanEdge · OpenIntervue</p></article><article><span>EDUCATION</span><h2>BIT, Bengaluru</h2><p>B.E. Information Science · 2024-2028<br/>CGPA: 9.0 / 10</p></article></div><div className="resume-document"><img src={resumePreview} alt="First page of Vignesh B S's supplied resume"/><a href={resume||'#'} target="_blank" rel="noreferrer">Open the public resume PDF ↗</a></div></section>}
 {page==='contact'&&<section className="contact-page"><a className="back-link" href="/" onClick={e=>navigate(e,'home')}>← Back to projects</a><div className="page-heading"><span className="eyebrow">CONTACT / BENGALURU, INDIA</span><h1>Got an idea?<br/><em>Let's talk.</em></h1><p>AI, automation or a product that needs to get built.</p></div><div className="contact-cards"><a href="mailto:vignesh.bs06@gmail.com"><span>EMAIL</span><strong>vignesh.bs06@gmail.com</strong><i>↗</i></a><a href="https://linkedin.com/in/vigneshbs-dev" target="_blank" rel="noreferrer"><span>LINKEDIN</span><strong>vigneshbs-dev</strong><i>↗</i></a><a href="https://github.com/vigneshbs33" target="_blank" rel="noreferrer"><span>GITHUB</span><strong>vigneshbs33</strong><i>↗</i></a></div><p className="contact-page-note">The links open your email app or the original profile. No form collects or stores your details.</p></section>}
<SiteMenu open={menu} close={()=>setMenu(false)} navigate={(e,name,href)=>{if(embedded){e.preventDefault();setPage(name);setTimeout(()=>{if(href.includes('#'))root.current?.querySelector(href.slice(href.indexOf('#')))?.scrollIntoView({behavior:'instant'});else root.current?.scrollTo({top:0,behavior:'instant'})},60)}}}/>
 {footer}
 {active&&<div className="dialog-overlay" onClick={()=>setActive(null)}><section role="dialog" aria-modal="true" aria-labelledby="project-dialog-title" className="project-dialog" onClick={e=>e.stopPropagation()}><button className="close-dialog" onClick={()=>setActive(null)} aria-label="Close project details">Close ×</button><span className="eyebrow">{active.category}</span><h2 id="project-dialog-title">{active.title}</h2><p className="dialog-lead">{active.description}</p>{active.details.map((s,i)=><div className="detail-row" key={s}><span>0{i+1}</span><p>{s}</p></div>)}<div className="dialog-links">{active.url&&<a href={active.url} target="_blank" rel="noreferrer">Project website ↗</a>}{active.code&&<a href={active.code} target="_blank" rel="noreferrer">Source code ↗</a>}</div><p className="dialog-note">Technical claims from Vignesh's supplied resume. This is a project description, not a live system or benchmark reproduction.</p></section></div>}
 </div>
}