import React,{useEffect,useRef,useState} from 'react';
function SketchMark({type='spark',className=''}){return <svg className={'sketch-mark '+className} viewBox="0 0 64 64" fill="none" aria-hidden="true"><g stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">{type==='spark'?<><path d="M32 4v56M7 14l50 36M7 50l50-36M4 32h56"/><circle cx="32" cy="32" r="9"/></>:type==='outsurance'?<><path d="M32 7v13M32 20L12 34v16M32 20l20 14v16M32 20v30"/><rect x="25" y="3" width="14" height="10" rx="2"/><circle cx="12" cy="53" r="6"/><circle cx="32" cy="53" r="6"/><circle cx="52" cy="53" r="6"/></>:type==='garuda'?<><rect x="7" y="12" width="39" height="25" rx="4"/><path d="M46 21l12-6v19l-12-6M25 37v10M13 55h25M25 47l-12 8M25 47l13 8"/><circle cx="27" cy="24" r="6"/></>:<><path d="M9 23v18M17 17v30M25 25v14M33 8v48M41 18v28M49 23v18M57 27v10"/></>}</g></svg>}
export default function ProjectGallery({projects,images,onOpen}){
 const host=useRef(null);const [current,setCurrent]=useState(0);
 useEffect(()=>{const el=host.current;if(!el)return;const obs=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('gallery-entered');setCurrent(Number(e.target.dataset.projectIndex))}})},{threshold:0,rootMargin:'-15% 0px -45% 0px'});el.querySelectorAll('.feature-project').forEach(e=>obs.observe(e));return()=>obs.disconnect()},[]);
 const tilt=e=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches||!matchMedia('(pointer:fine)').matches)return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--spot-x',(e.clientX-r.left)/r.width*100+'%');e.currentTarget.style.setProperty('--spot-y',(e.clientY-r.top)/r.height*100+'%');e.currentTarget.style.setProperty('--tilt-x',((e.clientY-r.top)/r.height-.5)*-5+'deg');e.currentTarget.style.setProperty('--tilt-y',((e.clientX-r.left)/r.width-.5)*5+'deg')};
 const reset=e=>{e.currentTarget.style.setProperty('--tilt-x','0deg');e.currentTarget.style.setProperty('--tilt-y','0deg')};
 return <section id="selected-work" className="project-gallery" ref={host}>
 <div className="gallery-masthead"><div><h2>Built to<br/><em>be useful.</em></h2></div><div className="gallery-intro"><SketchMark className="gallery-spark"/><p>From models to interfaces.<br/>A closer look at what I build,<br/>and what happens under the hood.</p><span className="gallery-count">03 PROJECTS / FROM MY RESUME ↓</span></div></div>
 <nav className="gallery-index" aria-label="Featured projects">{projects.slice(0,3).map((p,i)=><a key={p.id} href={'#case-'+p.id} className={current===i?'active':''}><span>0{i+1}</span>{p.title}<i>↘</i></a>)}</nav>
 <div className="gallery-features">{projects.slice(0,3).map((p,i)=><article id={'case-'+p.id} className={'feature-project feature-'+p.id} key={p.id} data-project-index={i}>
 <div className="feature-copy"><h3>{p.title}</h3><span className="feature-discipline">{['Applied machine learning','Edge vision','Multimodal AI'][i]}</span><p className="feature-one-liner">{p.line}</p><ul className="feature-resume-description">{p.resumeBullets.map(x=><li key={x}>{x}</li>)}</ul><div className="feature-flow" aria-label="Project workflow">{p.steps.map((x,j)=><React.Fragment key={x}><span>{x}</span>{j<3&&<i aria-hidden="true">→</i>}</React.Fragment>)}</div><button className="feature-open" onClick={()=>onOpen(p)}>Inside the project <span>↗</span></button><div className="feature-stack">{p.stack.map(x=><span key={x}>{x}</span>)}</div></div>
 <button className="feature-art" aria-label={'Explore '+p.title} onClick={()=>onOpen(p)} onPointerMove={tilt} onPointerLeave={reset}>
 <SketchMark type={p.id} className="art-blueprint"/><span className="art-index" aria-hidden="true">0{i+1}</span>
 {images[p.id]?<span className="browser-window"><span className="browser-chrome"><i/><i/><i/><span>{p.id==='outsurance'?'outsurance.vercel.app':'garuda-teal.vercel.app'}</span><b>↗</b></span><img src={images[p.id]} alt={p.title+' public website screenshot'}/></span>:<span className="classroom-concept"><span className="concept-top">SPARSH MUKTHI / INTERACTION STUDY</span><span className="concept-teacher"><SketchMark/><strong>A classroom<br/>that listens.</strong></span><span className="concept-waves" aria-hidden="true">{[6,13,9,19,13,6,13,22,9,15,6,13,9].map((h,j)=><i key={j} style={{height:h}}/>)}</span><span className="concept-response"><span>STUDENT → VOICE</span><strong>Ask. Interrupt. Learn.</strong><small>Speech + model routing + natural response</small></span><span className="concept-hand" aria-hidden="true">↑</span><span className="concept-badge">VOICE / HAND RAISE / 3D</span></span>}
 <span className="art-note">{p.id==='sparsh'?'Interaction concept, not a product screenshot':p.id==='garuda'?'Actual public login portal':'Actual public website'}</span><span className="art-open" aria-hidden="true">↗</span></button>
 <div className="feature-footer"><span className="feature-scribble">{['make the decision inspectable ↗','less video, more signal ↗','learning, without the wait ↗'][i]}</span><span className="feature-result"><span className="result-dial"><svg viewBox="0 0 96 96"><circle className="dial-track" cx="48" cy="48" r="39"/>{i<2&&<circle className="dial-arc" cx="48" cy="48" r="39" style={{strokeDasharray:245,strokeDashoffset:245*(1-([.85,.99,1][i]))}}/>}<path d="M48 3v6M48 87v6M3 48h6M87 48h6M16 16l5 5M75 75l5 5M16 80l5-5M75 21l5-5"/></svg><strong>{p.metric}</strong></span><span>{p.unit}<small>Project-reported specification</small></span></span></div>
 </article>)}</div>

 </section>
}
