import React,{useEffect,useRef,useState} from 'react';
const roles=[
 {company:'Fidelity Investments',role:'Upcoming Intern',date:'Upcoming',type:'Selected through campus placement',bullets:['Selected through campus placement for a two-month internship.']},
 {company:'LessonPlan',role:'AI Systems Developer',date:'Nov 2025 to Present',type:'AI systems',bullets:['Build and ship AI features for an EdTech platform: ML pipelines, agent workflows and RAG.','Own model serving, CI/CD and monitoring in production.']},
 {company:'GyanEdge',role:'Lead Developer',date:'Mar 2025 to Present',type:'Part-Time',bullets:['Lead development of a real-time online assessment platform on Supabase, from research and design through testing and release.']},
 {company:'OpenIntervue',role:'QA Engineer',date:'May 2025 to Jul 2025',type:'Intern',bullets:['Tested a live LLM interview platform for accuracy and consistency; wrote automated test plans and tracked latency.']}
];
function WorkGlyph({i}){return <svg viewBox="0 0 40 40" fill="none" aria-hidden="true"><g stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" strokeLinejoin="round">{i===0?<><path d="M9 30V10h22v20M14 16h12M14 22h12M14 30v-5h12v5"/><path d="M6 30h28"/></>:i===1?<><rect x="5" y="8" width="30" height="23" rx="3"/><path d="M10 15l5 5-5 5M20 25h10M16 4v4M25 4v4M16 31v5M25 31v5"/></>:i===2?<><path d="M6 12l14-5 14 5-14 5-14-5M9 17v10l11 6 11-6V17M20 17v16"/></>:<><path d="M12 5h16v6h5v24H7V11h5zM12 5v7h16V5M12 21l4 4 12-8M12 30h16"/></>}</g></svg>}
export default function WorkExperience(){const [opened,setOpened]=useState(1),host=useRef(null);useEffect(()=>{const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('work-arrived');obs.unobserve(e.target)}}),{threshold:.1});host.current?.querySelectorAll('.work-row').forEach(x=>obs.observe(x));return()=>obs.disconnect()},[]);return <section id="experience" className="work-experience" ref={host}><div className="work-heading"><h2>Work, over<br/><em>time.</em></h2><p>AI systems, product development<br/>and the testing behind them.</p></div><div className="work-ledger">{roles.map((r,i)=><article key={r.company} className={'work-row '+(opened===i?'work-expanded':'')}><span className="work-pin" aria-hidden="true"/><button className="work-trigger" onClick={()=>setOpened(opened===i?-1:i)} aria-expanded={opened===i} aria-controls={'role-detail-'+i}><span className="work-symbol"><WorkGlyph i={i}/></span><span className="work-primary"><span className="work-company">{r.company}</span><strong>{r.role}</strong><span className="work-type">{r.type}</span></span><span className="work-date">{r.date}</span><span className="work-toggle" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M5 12h14M12 5v14"/></svg></span></button><div id={'role-detail-'+i} className="work-details" hidden={opened!==i}><ul>{r.bullets.map(x=><li key={x}>{x}</li>)}</ul><span className="work-source">From my resume</span></div></article>)}</div></section>}
